### ISSUE TITLE
Running in Windows

### ISSUE THREAD

**Issue by krasnikau-andrei** [alexchandel/dfhack-remote#3]
Looks like websockify is not working in Windows. I spend a day trying to make it work (also using websockify.js). Is it possible to replace websockify with something else?

**Comment by krasnikau-andrei** [comment]
Is it possible to run it using Docker?

**Comment by alexchandel** [comment]
I'm sure it runs in Docker.  Could you open an issue on websockify & websockify.js with your errors please?  They worked on Windows when I tested it, and I'd like to document your errors for future users.

We ourselves may have to patch / get some poor urist to patch websockify.js either way.

**Comment by krasnikau-andrei** [comment]
Already resolved with websockify.js
